[versions]
# shaded libraries
screaming-lib = "2.0.3-SNAPSHOT"
simple-inventories = "2.0.3-SNAPSHOT"
bstats = "2.2.1"
commodore = "2.0"
hikari = "5.0.0"

# compileOnly libraries
# version of paper does not matter, we barely use the api here, we only have to choose one compatible with Java 11
paper = "1.16.5-R0.1-SNAPSHOT"
parties-api = "3.2.6"
perworldinventory-old = "1.11.5"
perworldinventory-kt = "2.3.1"
multiverse = "4.0.0"
jetbrains-annotations = "26.0.1"

# plugins
screaming-plugin-builder = "1.1.0-SNAPSHOT"
buildconfig = "3.0.2"
lombok = "8.11"

configurate = "4.1.2"
configurate-patched-gson = "4.1.2-sandals-patch"

[libraries]
# shaded libraries
# screaming-lib and simple-inventories are handled by plugin
commodore = { group = "me.lucko", name = "commodore", version.ref = "commodore" }
hikari = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikari" }
bstats = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bstats" }

# compileOnly libraries
paper = { group = "com.destroystokyo.paper", name = "paper-api", version.ref = "paper"}
parties-api = { group = "com.alessiodp.parties", name = "parties-api", version.ref = "parties-api" }
perworldinventory-old = { group = "me.gnat008", name = "perworldinventory", version.ref = "perworldinventory-old" }
perworldinventory-kt = { group = "me.ebonjaeger", name = "perworldinventory-kt", version.ref = "perworldinventory-kt" }
multiverse = { group = "com.onarandombox.multiversecore", name = "Multiverse-Core", version.ref = "multiverse" }
configurate-gson = { group = "org.spongepowered", name = "configurate-gson", version.ref = "configurate-patched-gson" }
configurate-yaml = { group = "org.spongepowered", name = "configurate-yaml", version.ref = "configurate" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations" }

[plugins]
screaming-plugin-builder = { id = "org.screamingsandals.plugin-builder", version.ref = "screaming-plugin-builder" }
screaming-plugin-slib = { id = "org.screamingsandals.plugin-slib", version.ref = "screaming-plugin-builder" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }